teams = {
    "NJNY": "NJ/NY Gotham",
    "POR": "Portland Thorns",
    "LA": "Angel City",
    "CHI": "Chicago Red Stars",
    "WAS": "Washington Spirit",
    "SD": "San Diego Wave",
    "NC": "NC Courage",
    "RGN": "OL Reign",
    "LOU": "Racing Louisville",
    "HOU": "Houston Dash",
    "ORL": "Orlando Pride",
    "KC": "KC Current",
}
colors = {
    "NJNY": "#000000",
    "POR": "#97262c",
    "LA": "#f8d5ce",
    "CHI": "#3cb5e4",
    "WAS": "#c20032",
    "SD": "#011e40",
    "NC": "#00416b",
    "RGN": "#002f87",
    "LOU": "#c5b4e1",
    "HOU": "#ff6a01",
    "ORL": "#60269e",
    "KC": "#62cac9",
}
text = {
    "NJNY": "#ffffff",
    "POR": "#ffffff",
    "LA": "#000000",
    "CHI": "#000000",
    "WAS": "#ffffff",
    "SD": "#ffffff",
    "NC": "#ffffff",
    "RGN": "#ffffff",
    "LOU": "#000000",
    "HOU": "#000000",
    "ORL": "#ffffff",
    "KC": "#000000",
}