class FAWSL:
    NAMES = {
        "ARS": "Arsenal",
        "AST": "Aston Villa",
        "BHA": "Brighton & Hove",
        "CHE": "Chelsea",
        "EVE": "Everton",
        "LEI": "Leicester City",
        "LIV": "Liverpool",
        "MNC": "Manchester City",
        "MNU": "Manchester United",
        "REA": "Reading",
        "TOT": "Tottenham",
        "WHU": "West Ham United",
    }
    COLORS = {
        "ARS": "#9C824A",
        "AST": "#480024",
        "BHA": "#0057B8",
        "CHE": "#001489",
        "EVE": "#00019e",
        "LEI": "#273e8a",
        "LIV": "#d3171e",
        "MNC": "#98c5e9",
        "MNU": "#DA291C",
        "REA": "#0032b9",
        "TOT": "#0f204b",
        "WHU": "#7A263A",
    }
    TEXT_COLORS = {
        "ARS": "#ffffff",
        "AST": "#94bee5",
        "BHA": "#ffffff",
        "CHE": "#ffffff",
        "EVE": "#ffffff",
        "LEI": "#ffffff",
        "LIV": "#ffffff",
        "MNC": "#1C2C5B",
        "MNU": "#FBE122",
        "REA": "#ffffff",
        "TOT": "#ffffff",
        "WHU": "#F3D459",
    }
